project:
  type: website
  output-dir: docs
  
website:
  site-url: hhtps://devicl.github.io/
  title: "Devi Canseco"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Data Viz"
        menu:
        - text: "Simpsons"
          href: dataviz.html
        - text: "Groundhog Predictions"
          href: dataviz2.html
        - text: "Federalist Papers Analysis"
          href: FedPapers.qmd
        - text: "English Education"  
          href: Riskprofile.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

