project:
  type: website
  output-dir: docs
  
website:
  site-url: hhtps://devicl.github.io/
  title: "Devi Canseco"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Data Viz"
        menu:
        - text: "Simpsons"
          href: dataviz.html
        - text: "Groundhog Predictions"
          href: dataviz2.html
        - text: "Federalist Papers Analysis"
          href: FedPapers.qmd
        - text: "English Education"  
          href: Riskprofile.qmd
        - text: "Ethical Analysis"
          href: ethics.qmd
        - text: "SQL project"
          href: sql.qmd
      - text: "DS002R Projects Presentation"
        href: webfix.qmd

format:
  html:
    theme:
      light: sandstone
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

