---
title: "Ethics in Predictive Analytics for Marketing"
description: |
  Discussion of the Target pregnancy prediction algorithm
  
author: Devi Canseco
date: April 15, 2025
format: html
---

Two articles:

-   *How Target leveraged predictive analytics to improve marketing ROI*. OvationMR. Retrieved from <https://www.ovationmr.com/how-target-leveraged-predictive-analytics/>

<!-- -->

-    Duhigg, C. (2012, February 16). *How companies learn your secrets*. *The New York Times Magazine*. <https://www.nytimes.com/2012/02/19/magazine/shopping-habits.html>

**Summary**

In 2012, the New York Times released an article with the headline, "How Companies Learn Your Secrets". The big story of this article was how Target asked a statistician, Andrew Pole, whom they hired to identify pregnant customers so they could tailor their marketing before any other company could capitalize on the spending habits of new parents. The article further dives into the work of predictive analytics and how companies use customer habits to determine how to better sell a product. The reporter, Charles Duhigg, states that when Target was made aware of his article, they stated that they were in compliance with Privacy Laws and critiqued inaccuracies in his reporting, but would not elaborate or meet with him for further discussion. Further development by Pole on the targeted advertisement was to address possibly scaring their customers by alerting them they knew their personal profile or information before they had a purchase history of it. To overcome this, a layer of mixed advertisement with targeted advertisement would hide this.

OvationMR takes the prior article discussed as a launching point for their own advertisement. The website uses the New York Times article as a case study to learn strategies and marketing growth from. Calling its resolution a success, with Target being able to "maintain its customer relationships while respecting their privacy."

-   **What was the consent structure for recruiting participants? Were the participants aware of the ways their data would be used for research? Was informed consent possible? Can you provide informed consent for applications that are yet foreseen?**

    From the New York Times article, it is shown the consent structure is not fully seen by the customer as it is a silent agreement that purchase history will be retained by the company. In this case, like in many marketing departments, a user profile is created for the customers to track engagement across what the store offers, including coupons, surveys, refunds, purchases, etc. The customers were not aware that Target would transform the data collected on them into a prediction system of their potential pregnancy status. Informed consent of the full situation was not sought after since this fits within company privacy laws that allow it to maintain information for marketing purposes, but a concent is implied to give the company data when purchasing from them. Although the purpose could be deduced early on when advertisements specifically showed baby items alone.

-   **What was the data collection process? Were the observations collected ethically? Are there missing observations?**

    The data collection process was based on identifying customer behavior patterns and technically on legal grounds and respecting privacy, as Target only made conclusions based on what customers would purchase. OvationMR encourages the practice of data tracking with existing models and third party resources that follow privacy laws. This further drives the point of widespread data tracking.

-   **Is the data identifiable? All of it? Some of it? In what way? Are the data sufficiently anonymized or old to be free of ethical concerns? Is anonymity guaranteed?**

    While this data is not publicly available, in earlier advertising efforts, it could be deduced that pregnancy was implied and therefore gave a piece of private information to whoever encountered the advertisement in connection with the customer, as was the case for the angry father and his teenage daughter. The revised advertisement model better hides the privacy issue as it is theoretically undetectable even by the target customer. However, holding the information of someone being pregnant without their knowing a privacy issue on its own, as the customer has not sought to make this personal information available to Target. Forming such a sensible data set can risk customer privacy if there was a data breach. If third-party advertisement, as brought up by OvationMR, is taken into consideration, then information from Target can end up elsewhere.

-   **10.Respect and invite fair criticism while promoting the identification and open discussion of errors, risks, and unintended consequences of our work.**

    OvationMR reviewed the criticism Target received as a need to reanalyze their marketing strategy rather than an overstep. From the New York Times, it is reported that Target refused to give a statement to Pole, which means in light of their predictive analytics, they failed a point of the manifesto. By refusing to engage in conversation over their data collection and analysis, they in some form acknowledged that it was not the most well-handled data. It refused direct criticism but answered to customer criticism not by removing the ads but by disguising them.
